### ISSUE TITLE
Multi select is not working properly when selection attribute is binded

### ISSUE THREAD

**Issue by PrashantkumarWebDeveloper** [pozil/sfdc-ui-lookup-lwc#101]
With multi-select, if 'selection' attribute is provided, its causes issues in the second selection. Probably because after the first selection when data is propagated to the 'selection setter' it is setting _isDirty to false and this is preventing the next search result to appear in the search result.

**Comment by pozil** [comment]
Hi @PrashantkumarWebDeveloper thanks for reaching out. I'm not sure to understand how to reproduce the issue.
The sample form shipped with this project uses a bounded `selection` attribute and I can select multiple items in the lookup without issues. Can you provide more details?

**Comment by PrashantkumarWebDeveloper** [comment]
Hi @pozil thanks for the quick response. I also tried to replicate it in some sample code but couldn’t replicate it. It seems, in my case lookup input is loosing focus somehow. I am closing this issue.

**Comment by PrashantkumarWebDeveloper** [comment]
Hi @pozil thanks for the quick response. I also tried to replicate it in some sample code but couldn’t replicate it. It seems, in my case lookup input is loosing focus somehow. I am closing this issue.

**Comment by PrashantkumarWebDeveloper** [comment]
Hi @pozil thanks for the quick response. I also tried to replicate it in some sample code but couldn’t replicate it. It seems, in my case lookup input is loosing focus somehow. I am closing this issue.
