### ISSUE TITLE
need details on event.target.getSelection()

### ISSUE THREAD

**Issue by padmaneela123** [pozil/sfdc-ui-lookup-lwc#106]
in handleLookupSelectionChange(event) all I am getting is selected ID but not complete object attribute/field values.  I have situation on parent we have two lookups I want  check based sObjectType value I want to call different APEX method. Please advise.

**Comment by pozil** [comment]
HI @padmaneela123, I'm not sure to fully understand your use case.
If I get this right, you need to pass extra data to the search handler. This is documented here: [Passing custom data to JavaScript and Apex](https://github.com/pozil/sfdc-ui-lookup-lwc#passing-custom-data-to-javascript-and-apex-optional)

**Comment by padmaneela123** [comment]
Thanks Philippe for the quick response.

In my requirement on page i add two lookup fields , one is to select User
and other one is badge.
Now in handleLookupSelectionChange(even) method event.detail is giving
associated selected records ids . but I want to retrieve sObjectType but I
am not able to succeed it most likely CustomEvent of selectionchange is
just returning selected ids could be possibility .

but in the documentation below I read that I can pull all the fields of
LookupSearchResults.

// Or, get the selection objects with ids, labels, icons...    const
selection = event.target.getSelection();

Would you please help me to extract data from selection .

Thanks
Padma.

**Comment by pozil** [comment]
Ok, now I understand a bit better.

If you're working with different objects in separate lookups, I would advise you to create different `handleLookupSelectionChange` methods and dedicated Apex search endpoints so that there's no confusion on the object types.

```html
<c-lookup
  onsearch={handleSearchUser}
  onselectionchange={handleUserSelectionChange}
  label="Search for a user">
</c-lookup>
<c-lookup
  onsearch={handleSearchBadge}
  onselectionchange={handleBadgeSelectionChange} 
  label="Search for a badge">
</c-lookup>
```

If you really don't want to do this then, proceed with my [initial suggestion](https://github.com/pozil/sfdc-ui-lookup-lwc#passing-custom-data-to-javascript-and-apex-optional) and add a custom data attribute (`data-type` in the example below) that gives you the object type.
```html
<c-lookup
  onsearch={handleSearch}
  onselectionchange={handleSelectionChange}
  label="Search for a user"
  data-type="User">
</c-lookup>
<c-lookup
  onsearch={handleSearch}
  onselectionchange={handleSelectionChange} 
  label="Search for a badge"
  data-type="Badge">
</c-lookup>
```

Then, figure out the object type in JS:
```js
handleSelectionChange(event) {
    const lookupElement = event.target;
    alert(lookupElement.dataset.type); // User or Badge
}
```

**Comment by padmaneela123** [comment]
Thanks  Philippe.

I went ahead with a separate selection method.  Now the challenge I have is
, when I send event.detail value to apex i am getting below error , i
changed it Id same error.

Lookup error {"status":500,"body":{"message":"Value provided is invalid for
action parameter 'recipientID' of type 'String'"},"headers":{}}

**Comment by padmaneela123** [comment]
Thanks for the details.
