### ISSUE TITLE
Drop-down disappear while click on vertical scrollbar

### ISSUE THREAD

**Issue by Sourabh42** [pozil/sfdc-ui-lookup-lwc#118]
In lookup component when I click on vertical scrollbar to scroll down then the drop-down disappear. This is urgent requirement and need to fix this issue urgently.can u reply asap.

**Comment by pozil** [comment]
Hi @Sourabh42 thanks for reaching out. Just be clear, I don't deal with "urgent" issues or requirements. This is an open source project and there's no guaranteed support or SLAs.

Here are some potential workarounds while I investigate the issue:
- can use the mouse wheel or keyboard navigation.
- reduce the number of search results displayed in the lookup.

**Comment by pozil** [comment]
I tried to reproduce the issue without success:

![lookup-scroll](https://user-images.githubusercontent.com/5071767/183030730-e5aafbc1-e90d-42f6-8f31-6f21ff9b181e.gif)

I'm able to use the click on the scroll bar or use the mouse wheel.
Can you share more about your environment (browser, OS) or you configuration?

**Comment by Sourabh42** [comment]
It's working.

Thanks for your help
