### ISSUE TITLE
'handleBlur' method assigned to input text box incorrectly hides dropdown when dropdown scrollbar is used

### ISSUE THREAD

**Issue by CGaryDesigns** [pozil/sfdc-ui-lookup-lwc#12]
When attempting to use the scrollbars in the listbox that appears after search returns items, the listbox is hidden because the input text element loses focus. The textbox itself losing focus causes the handleBlur method to fire, which in turn will set the components 'hasFocus' to false, and hide the listbox of results.

**Comment by pozil** [comment]
Hi @CGaryDesigns, can you tell me which OS and browser are you using?
I just tried on macOS Mojave with Chrome and Firefox and the list box and scroll bar work fine.
