### ISSUE TITLE
Show All Results option in custom lookup field

### ISSUE THREAD

**Issue by ntimesc** [pozil/sfdc-ui-lookup-lwc#123]
Hi, 

I have used your component to implement custom look fields with some extra detailed information

Was just wondering whether we have an option of  **Show All Results for "text"**, just like we have in standard lookup field ?

![image](https://user-images.githubusercontent.com/5063898/203965641-2962e878-257c-478f-aa37-65c0263abed1.png)

here is the screenshot of the component that you have developed 

![image](https://user-images.githubusercontent.com/5063898/203965867-feb3a476-07ac-4855-94bf-973c740082a9.png)

**Comment by pozil** [comment]
Hi @ntimesc, I'm not clear on the behavior of this "Show all results" item. What's the expectation here?
