### ISSUE TITLE
Result Title not center aligned

### ISSUE THREAD

**Issue by satish-vsrs** [pozil/sfdc-ui-lookup-lwc#128]
The result Title starts at the top of the form. This works well if there is a result SubTitle. However, if there is no result SubTitle, the result Title should be aligned at the center. As shown in the screenshot, it aligned to the top.
![image (1)](https://user-images.githubusercontent.com/48604692/220972027-20d0cff4-1f54-4881-bce7-56ba3b8577f9.png)

**Comment by pozil** [comment]
Hi @satish-vsrs, thanks for reporting this but I couldn't reproduce the issue with the latest version of the lookup.
This is what I get when I don't provide a subtitle in result items:
<img width="691" alt="Screenshot 2023-02-24 at 13 45 15" src="https://user-images.githubusercontent.com/5071767/221182374-1113e514-3470-4a67-b262-25533a1774c2.png">

Can you make sure that you set `LookupSearchResult.subtitle` values to `null`?

**Comment by satish-vsrs** [comment]
Thanks, This is working fine once I set subtitle to null.
