### ISSUE TITLE
Use in Lightning Datatable

### ISSUE THREAD

**Issue by banderson-stripe** [pozil/sfdc-ui-lookup-lwc#130]
@pozil I was able to get the Lookup to function correctly by using it in a `editTemplate` as defined in the [Custom Data Type](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.data_table_custom_types_editable).

<img width="356" alt="image" src="https://user-images.githubusercontent.com/108089161/221892848-1573662a-c2a4-45fd-8619-90de49d7e353.png">

However, I did need to add a public API method to the `lookup.js` file called `validity()` as defined in the Custom Data Type documentation above:

```javascript
@api
get validity() {
    return true;
}
```

I am just returning `true` since I can't think of any validations for my use case.

**Comment by pozil** [comment]
Just added this public property in the latest release v2.20.0.
