### ISSUE TITLE
Auto open options on clear for single select combobox 

### ISSUE THREAD

**Issue by manish3344** [pozil/sfdc-ui-lookup-lwc#134]
Hello,

When we try to change the selected option and re-select again for single select lookup we have to do 2 clicks one for clearing the selection and other for opening the default options again which can automatically open like how the lookup works on salesforce record pages giving the users a better experience.

I checked that the component does not expose any .focus() methods to do so, can we support this feature?
All we need is a new api like blur

```
    @api
    focus() {
        this.template.querySelector('input')?.focus();
    }
```

**Comment by pozil** [comment]
Hi @manish3344 and sorry for the delay but this is a good idea.
I just implemented the `focus()` method in v2.22.0.
