### ISSUE TITLE
TypeError: Cannot read property 'setSearchResults' of null

### ISSUE THREAD

**Issue by jgaiotto** [pozil/sfdc-ui-lookup-lwc#14]
Hi Philippe,

I ran into an issue where the target of the onsearch event is null.
I cannot display any results...

Interesting fact, it becomes null after to call to Apex. Weird stuff.

Here is the code :
```apex
handleUserSearch(event) {
	console.log('before apex');
	// is false
	console.log(event.target === null); 

	search(event.detail)
		.then(results => {
			console.log('after apex');
			// is true
			console.log(event.target === null); 

			// the following line raises "TypeError: Cannot read property 'setSearchResults' of null" 
			event.target.setSearchResults(results);
		})
		.catch(error => {
			this.dispatchEvent(
				prepareToast('Erreur', 'Une erreur est survenue durant la recherche : ' + error,
					VARIANT.ERROR, MODE.DISMISSABLE)
			);
		});
}
```

As per your documentation, my Apex method is Cacheable.
Just tell me what you need to know about my code, but I basically installed the component in my org.

Thank you for your help.

### Workaround
This is a dirty workaround which allows me to use the component, but I would prefer not to do it...
I populated the `custom-key` attribute, which allows me to retrieve the component.

```apex
handleUserSearch(event) {
	// Get the key of the lookup
	let lookupKey = event.target.getkey();

	search(event.detail)
		.then(results => {
			// Do this disgusting forEach to identify the proper lookup component
			this.template.querySelectorAll('c-lookup').forEach(element => {
				if (element.getkey() === lookupKey) {
					element.setSearchResults(results);
				}
			});
		})
		.catch(error => {
			this.dispatchEvent(
				prepareToast('Erreur', 'Une erreur est survenue durant la recherche : ' + error,
					VARIANT.ERROR, MODE.DISMISSABLE)
			);
		});
}
```

**Comment by pozil** [comment]
Hi @jgaiotto, you need to store `event.target` in the context of the `handleUserSearch` function because the promise returned by the `search` Apex function is executed asynchronously.

You can do that with a `const` like so:

```js
handleUserSearch(event) {
  const { target } = event;
  search(event.detail).then(results => {
    // This is called asynchronously so you can't rely on event.target here
    target.setSearchResults(results);
  });
}
```

**Comment by jgaiotto** [comment]
Well, thanks for your help !
Looks like I completely missed that line in your example of your readme, sorry about that.

Hope that issue will help anyone who prefer typing over copying/pasting code from examples...
