### ISSUE TITLE
Searching with minSearchTermLength=0 does not work initially

### ISSUE THREAD

**Issue by TrangOul** [pozil/sfdc-ui-lookup-lwc#142]
We have the following use case: we have an object A with child objects B and C. We also have a lookup from B to C, which should be restricted to Cs related to B's parent A - meaning that there will be a small number of Cs to select from (and also one another, more complex scenario, but you get the idea).
Long story short, we'd like to be able to see all the search results without typing the search term (but retaining that possibility).

Even with `minSearchTermLength` is set to 0, the component initially does not display any results. We need to type one character and then remove it - because search is run only on `input` event, not on `focus`.

Please make it possible to run the search immediately, either with a flag or a special treatment when `minSearchTermLength=0`.

**Comment by pozil** [comment]
Hi @TrangOul, using `setDefaultResults(results)` is a better fit for this use case.
It behaves just like this and won't require code changes.

![Screenshot 2023-08-04 at 09 33 24](https://github.com/pozil/sfdc-ui-lookup-lwc/assets/5071767/43da50b6-63e3-40fb-b29e-3b46fd965e04)
