### ISSUE TITLE
Missing tooltip when option title is very long

### ISSUE THREAD

**Issue by manish3344** [pozil/sfdc-ui-lookup-lwc#143]
I see a aria-label already present on the div with class `slds-listbox__option` , the ellipsis is already working for long options but adding a tooltip would be more helpful to the user visually to know what the option title says before making a selection.
![image](https://github.com/pozil/sfdc-ui-lookup-lwc/assets/11214889/57267e65-f260-49db-a09b-6e7cc63c4610)

**Comment by pozil** [comment]
Hi @manish3344 great feedback and easy to address. I just released a new version with the tooltips.

**Comment by manish3344** [comment]
Thank you for the quick response and resolution.
