### ISSUE TITLE
Help: Once New record created auto populate the lookup with it

### ISSUE THREAD

**Issue by sivasank4sfdc** [pozil/sfdc-ui-lookup-lwc#150]
Hi Pozil,

Good Day! trust you are doing great.

It needs small help, I'm trying to practice it. But I need your help with inputs on Creating **New Account**, I want auto-populate the lookup to be populated with the same record.

I'm not able to pass the callback function and auto-populate the lookup with the newly created record.

Thank you
Sivasankar

**Comment by pozil** [comment]
Hi @sivasank4sfdc, unfortunately the lookup doesn't support this.

Here is the sequence of events around the record creation:
1. The user clicks on the new record option from the lookup.
2. The lookup calls the pre-navigate callback. This is where you may save the form state (other field values) to avoid loosing your work. It's important to note that the new record is **not yet created at this point**.
3. The lookup opens the record creation form thanks to [lightning/navigation](https://developer.salesforce.com/docs/platform/lwc/guide/use-navigate-default.html). At this point, lookup is no longer part of the execution context so you can't retrieve the new record.
