### ISSUE TITLE
Adding 2 lookup on same component and its not working.

### ISSUE THREAD

**Issue by nkjmetacube** [pozil/sfdc-ui-lookup-lwc#24]
On second lookup, list is not getting displayed.

**Comment by pozil** [comment]
Hi @nkjmetacube, can you make sure that you have defined different valid functions for the `onsearch` handler function of the lookups?

```xml
<c-lookup onsearch={handleSearch} ...
```

**Comment by nkjmetacube** [comment]
Hi Pozil, Thanks for your response. I have defined 2 separate handler search function for both the lookups. Please let me know how to fix it or I am doing anything wring.

**HTML:**
<c-lookup
                selection={initialSelection}
                errors={errors}
                onsearch={handleSearchFrom}
                onselectionchange={handleSelectionChange}
                label="Search"
                placeholder="Search Salesforce"
                is-multi-entry={isMultiEntry}
            >
            </c-lookup>
<c-lookup
                selection={initialSelection}
                errors={errors}
                onsearch={handleSearchTo}
                onselectionchange={handleSelectionChange}
                label="Search"
                placeholder="Search Salesforce"
                is-multi-entry={isMultiEntry}
            >
            </c-lookup>
**JS**

 handleSearchFrom(event) {
        apexSearch(event.detail)
            .then(results => {
                this.template
                    .querySelector('c-lookup')
                    .setSearchResults(results);
            })
            .catch(error => {
                this.notifyUser(
                    'Lookup Error',
                    'An error occured while searching with the lookup field.',
                    'error'
                );
                // eslint-disable-next-line no-console
                console.error('Lookup error', JSON.stringify(error));
                this.errors = [error];
            });
    }

 handleSearchTo(event) {
        apexSearch(event.detail)
            .then(results => {
                this.template
                    .querySelector('c-lookup')
                    .setSearchResults(results);
            })
            .catch(error => {
                this.notifyUser(
                    'Lookup Error',
                    'An error occured while searching with the lookup field.',
                    'error'
                );
                // eslint-disable-next-line no-console
                console.error('Lookup error', JSON.stringify(error));
                this.errors = [error];
            });
    }

**Comment by pozil** [comment]
Thanks for the code @nkjmetacube. The problem is that you're using the same `c-lookup` selector in your search handlers:
```js
this.template.querySelector('c-lookup').setSearchResults(results);
```

Add an attribute like a css class to differentiate the two lookups and change your selector to be more specific. Note that you can't use and `id` due to LWC specificities.

You could do:
```html
<c-lookup
                selection={initialSelection}
                errors={errors}
                onsearch={handleSearchFrom}
                onselectionchange={handleSelectionChange}
                label="Search"
                placeholder="Search Salesforce"
                is-multi-entry={isMultiEntry}
                class="searchFrom"
>
````

```js
this.template.querySelector('c-lookup.searchFrom').setSearchResults(results);
```

**Comment by nkjmetacube** [comment]
Thanks Pozil for your help.
