### ISSUE TITLE
Sort functionality

### ISSUE THREAD

**Issue by robmcmen** [pozil/sfdc-ui-lookup-lwc#27]
First off- LOVE this component.  

Simple possible improvement (I have it working in my org) add a custom sort functionality (or at least a place holder to help configure) on Title so results how up in a more deterministic order?

e.g. Add the following method to LookupSearchResult.cls:
```
        //Compare
        public Integer compareTo(Object compareTo){
            // Cast arg to LookupSearchResultWrapper
            LookupSearchResult compareToResult = (LookupSearchResult) compareTo;
            return this.getTitle().compareTo(compareToResult.getTitle());
        }
```

Then just add a results.sort() in your controller before returning to UI.

**Comment by pozil** [comment]
That's a great idea, thanks @robmcmen.
I just released a new version with that feature.
