### ISSUE TITLE
Not able to use two lookup components inside one parent component

### ISSUE THREAD

**Issue by ajay1909** [pozil/sfdc-ui-lookup-lwc#3]
Hi Team,

I have been trying to use your LWC lookup(Multiple selection) component inside my parent LWC component, it does work like a charm when used just once inside complete component, but when used twice inside the same LWC component, it doesn't seem to work properly and didn't fetch me the results for second lookup field. 

Could you please help me with this issue.

Thanks
Ajay

**Comment by pozil** [comment]
Hi @ajay1909. Can you share some code that allows to reproduce the issue?

**Comment by JigarLakhaniAtJade** [comment]
Hi Philippe,

Thank you so much. Very Helpful.
Having same issue related to using Lookup Component twice in same component.

Tried to resolve the issue but couldn't find out the solution. Can you please share the solution if you already have it?

Thanks in advanced.

Below is the code to replicate the issue. You can update "sampleLookupContainer.html" with below code.

`<template>
    <lightning-card title="Sample Lookup (Lightning Web Component)">
        <div class="slds-form slds-form_stacked slds-m-around_xx-large">

            <lightning-input type="checkbox" label="Is mutli entry lookup"
                checked={isMultiEntry} onchange={handleLookupTypeChange}></lightning-input>

            <c-lookup selection={initialSelection} errors={errors}
                onsearch={handleSearch} onselectionchange={handleSelectionChange}
                label="Search1" placeholder="Search Salesforce" is-multi-entry={isMultiEntry}>
            </c-lookup>

            <c-lookup selection={initialSelection} errors={errors}
                onsearch={handleSearch} onselectionchange={handleSelectionChange}
                label="Search2" placeholder="Search Salesforce" is-multi-entry={isMultiEntry}>
            </c-lookup>

            <lightning-button variant="brand" label="Submit" onclick={handleSubmit}></lightning-button>
        </div>
    </lightning-card>
</template>`


Jigar Lakhani

**Comment by JigarLakhaniAtJade** [comment]
Greetings!!!

Just got the solution.

Updated "handelSearch" method with minor change and it worked.

**Old**
`.then(results => {
                this.template.querySelector('c-lookup').setSearchResults(results);
            })`

**New**
`.then(results => {
                this.template.querySelectorAll('c-lookup').forEach(element => {
                    element.setSearchResults(results);
                });
            })`

Hope, it will be full proof solution.
Thank you again.

Jigar Lakhani

**Comment by pozil** [comment]
Hi @JigarLakhaniAtJade, glad to hear that you've found the issue.

**Comment by febriantarigan** [comment]
Hi @JigarLakhaniAtJade, 

Thanks for the solution, however the solution that you provided will show result on other lookup field as well because it set element searchresult for every 'c-lookup'.

I have found better solution so it will show the result on the specific lookup field by adding `<div class="search1"/>` with class defined as a wrapper inside the `<c-lookup/>` tag.

here is the code
**HTML**
```
<div class="search1">
<c-lookup selection={initialSelection} errors={errors}
            onsearch={handleSearch} onselectionchange={handleSelectionChange}
            label="Search1" placeholder="Search Salesforce" is-multi-entry={isMultiEntry}>
        </c-lookup>
</div>
<div class="search2">
        <c-lookup selection={initialSelection} errors={errors}
            onsearch={handleSearch} onselectionchange={handleSelectionChange}
            label="Search2" placeholder="Search Salesforce" is-multi-entry={isMultiEntry}>
        </c-lookup>
</div>
```

**JS**
```
//to get c-lookup for search1
.then(results => { 
let searchOne = this.template.querySelector('.search1'); 
searchOne.querySelector('c-lookup').setSearchResults(results); 
})

//to get c-lookup for search1
.then(results => { 
let searchTwo = this.template.querySelector('.search2'); 
searchTwo.querySelector('c-lookup').setSearchResults(results); 
})
```

Hope, it will be useful solution.
Thanks,

Febrian
