### ISSUE TITLE
Is there a way to set the value with defaults? 

### ISSUE THREAD

**Issue by Katulka** [pozil/sfdc-ui-lookup-lwc#39]
I'd like the lookup to be pre-populated with the value on page load, then user can change it.  Any suggestions that match your component?

**Comment by pozil** [comment]
Yes, with the `selection` attribute.
Please take a look at the sample app for an example:
https://github.com/pozil/sfdc-ui-lookup-lwc/blob/master/src-sample/main/default/lwc/sampleLookupContainer/sampleLookupContainer.js
