### ISSUE TITLE
License for this project

### ISSUE THREAD

**Issue by pgjensen** [pozil/sfdc-ui-lookup-lwc#4]
Hi is there a particular open source license tied to this project?

**Comment by pozil** [comment]
Hi Paul, thanks for asking. I forgot to include the license file.
I've chosen to license this under Apache 2.0 just like the Aura version of the component.

**Comment by joeythomaschaske** [comment]
@pozil Is there a preferred method of delivering the license to the user?

If I'm making an app exchange listing may I just include it in the documentation download area?

**Comment by pozil** [comment]
Hi @joeythomaschaske, yes please do this and feel free to share a link. I'm always happy to see great uses of this component.
