### ISSUE TITLE
Using the selection={initialLookup} option causing problems searching

### ISSUE THREAD

**Issue by Katulka** [pozil/sfdc-ui-lookup-lwc#40]
![image](https://user-images.githubusercontent.com/6976559/79272049-dc8dbc00-7e6e-11ea-8e15-1249ff7f3e39.png)

I'm using selection= and on page load the lookup is populated correctly. 

When I click the x to remove the value, then start to type for a different option, I get the attached error.

If I remove the selection= attribute, everything works again just without my default.

At the failing line, curSelection is {} 
![image](https://user-images.githubusercontent.com/6976559/79272586-aa308e80-7e6f-11ea-82b4-dcc44e6eb55c.png)

**Comment by Katulka** [comment]
Hi @pozil,

I have figured this out and it was an issue on my side.  I was forgetting that "selection" must always be an array, and when blank an empty array.    

You can see in my debug log that this.curSelection was an object {}, that's supposed to be []

So no bug, unless you wanted to update the setter for "selection" to handle object(for single select) or array for multi.

**Comment by pozil** [comment]
Hi @Katulka, thanks for the feedback. I've added that feature to the lookup: you can now set a single object or an array as the initial selection.
