### ISSUE TITLE
New feature, can I pull request?

### ISSUE THREAD

**Issue by Katulka** [pozil/sfdc-ui-lookup-lwc#42]
I'd like to contribute to a new branch with a PR.  The ability to clear the selection from a new api method, it's helping out a lot with my lwc components where I am doing a lot of screen refresh, reuse components from logic outside of the lookup.

**Comment by pozil** [comment]
Hi @Katulka, thanks for the proposal but you don't need an extra method to do that.
All you need to do is to reassign an empty array to the property used for initial selection.

Try that in the sample app:

Add a "Clear" button in `sampleLookupContainer.html`:
```html
<lightning-button variant="brand" label="Clear" onclick={handleClear}></lightning-button>
```

Add a handler for the button in `sampleLookupContainer.js`:
```js
handleClear() {
  this.initialSelection = [];
}
```

**Comment by Katulka** [comment]
That's interesting, I did try that but it would not clear. Maybe my intialSelection wasn't being tracked.. but I've had issue with that in the past. That's why I made the method in the lookup.js. 

@api
    clearSelection() {
        this.curSelection = [];
        this.isDirty = true;
        // don't bubble up event, prevent recursion
    }

**Comment by pozil** [comment]
Actually, `isDirty` needs to be set to `false` because we trust the developer to pass a valid value (unlike what the user enters).

This brings an interesting point, I'll add that flag reset to the lookup selection setter and I'll add an example that lets you clear the lookup.
