### ISSUE TITLE
Down button behavior (enhancement)

### ISSUE THREAD

**Issue by permrevolution** [pozil/sfdc-ui-lookup-lwc#47]
Hi creators,

Fantastic lookup, thanks so much.

1. Enter text on a desktop browser
2. It displays selection options below the lookup.
3. Press the down button on your keyboard
---> Nothing happens

When you do this on the Salesforce component lookup it handles the down press elegantly and you can select an option with the keyboard enter button (no mouse needed). Any way you / I can add this behavior?

Again, mille mercis.

**Comment by pozil** [comment]
Thanks for the feedback @permrevolution.

Keyboard support is unfortunately not part of the [SLDS blueprint](https://lightningdesignsystem.com/components/lookups/#site-main-content) from which this component is based. This means that we need to add a bit of JS code to implement it.
The good news is that this feature is being proposed in PR #45.

**Comment by pozil** [comment]
Feature moved to PR #50. Waiting for review before integration.

**Comment by pozil** [comment]
PR merged, you can now enjoy keyboard navigation in the latest release :)
