### ISSUE TITLE
Add parameters in search method

### ISSUE THREAD

**Issue by nayanDowerah** [pozil/sfdc-ui-lookup-lwc#52]
Hello,

I am trying to add this search functionality on a detail page of a record. For example, if I add this component on the account record page, I want it to only search for the child contacts associated with that particular account record.

However I am struggling to achieve this.

Is there a way to populate the second parameter in the method that is called while the search is made - **public static List<LookupSearchResult> search(String searchTerm, List<String> selectedIds) {**

ie. if I could send the recordId of the current record page as the second parameter (selectedIds) or even a separate parameter, I think I will be able to fulfil the requirement, by customizing the query.

Is there a way to perhaps add a new parameter to this method?

Or do you have a suggestion to workaround this sort of a requirement?

Thanks in advance for your help.

Regards
Nayan

**Comment by pozil** [comment]
Hi @nayanDowerah, the `search(String searchTerm, List selectedIds)` endpoint method signature is only provided as an example. You have full control over it so you can add extra parameters without modifying the lookup.
All you need to do is to remember to pass those extra parameters when you call `search` from within the `handleSearch` JS function.

For example, you could build custom `searchParams` object that you pass to the Apex search method like:
```js
handleSearch(event) {
    const target = event.target;
    const searchParams = {
        searchTerm: event.detail.searchTerm,
        selectedIds: event.detail.selectedIds,
        myCustomParam: this.myCustomParam
    };
    apexSearch(searchParams)
        .then(results => {
            target.setSearchResults(results);
        })
        .catch(error => {
            // TODO: handle error
        });
}
```

What you can't modify is:
- the info contained in the event that you get in `handleSearch`
- the parameters of `setSearchResults`

**Comment by nayanDowerah** [comment]
Thanks for your response @pozil !!

I realized that this was a simple maneuver after seeing your post. 

Thanks for this excellent and powerful component. Hoping to utilize it suitably now.
