### ISSUE TITLE
Using the selection={initialLookup} option causing problems searching first time.

### ISSUE THREAD

**Issue by ravibarnwal** [pozil/sfdc-ui-lookup-lwc#54]
I am passing selection={initialLookup} option with array of LookupSearchResult. Everything working correctly but on first time load search is not working. After click outside of input field and again trying to search then working fine.

![image](https://user-images.githubusercontent.com/7465670/92098067-6a564d80-edf6-11ea-9f7e-2626e35383ba.png)

**Comment by pozil** [comment]
Hi @ravibarnwal thanks for reaching out. I'm struggling to reproduce the issue you described.

Can you try to reproduce the issue on the repository sample so that we test the same thing?
1. Open `src-sample/main/default/lwc/sampleLookupContainer/sampleLookupContainer.js`
1. Change line 12 to `isMultiEntry = true;`

Let me know if you still have the issue.

**Comment by pozil** [comment]
Any updates @ravibarnwal ?

**Comment by ravibarnwal** [comment]
Hi @pozil 
Thanks for your response. When I am trying with **selection={initialSelection}** and used wired method to get value for **initialSelection**  and used this code in my component 
`            <c-lookup
                selection={initialSelection}
                errors={errors}
                onsearch={handleLookupSearch}
                onselectionchange={handleLookupSelectionChange}
                label="Search"
                placeholder="Search Salesforce"
                is-multi-entry={isMultiEntry}
                required
            >
            </c-lookup>` then above problem occurs.
Anyway I fixed this error using 
<template if:true={initialSelection}>
            <c-lookup
                selection={initialSelection}
                errors={errors}
                onsearch={handleLookupSearch}
                onselectionchange={handleLookupSelectionChange}
                label="Search"
                placeholder="Search Salesforce"
                is-multi-entry={isMultiEntry}
                required
            >
            </c-lookup>
</template>

Thanks for great reusable component.

**Comment by pozil** [comment]
Thanks for letting me know. I'm happy to hear that you find this component useful.
