### ISSUE TITLE
Error getRecentlyViewed

### ISSUE THREAD

**Issue by Gonzalez8** [pozil/sfdc-ui-lookup-lwc#55]
I have an error when I put the LWC on a record page and when I change from a tab to another I get the error. The problem is that this.template.querySelector(c-lookup) it is null. I don't know how I can force that the component lookup it is loaded before the wire.
![image](https://user-images.githubusercontent.com/6625310/94032669-75cae200-fdc0-11ea-9365-23f1e97d14a8.png)

**Comment by pozil** [comment]
Hi @Gonzalez8, thanks for reporting this issue. I've updated the sample app and [added some documentation](https://github.com/pozil/sfdc-ui-lookup-lwc#providing-default-search-results-ptional) to address that.
Let me know if it solves your problem.

**Comment by pozil** [comment]
Hi @Gonzalez8 any update?

**Comment by Gonzalez8** [comment]
Thanks now it's working well :)
