### ISSUE TITLE
Surface `_searchTerm` to the API

### ISSUE THREAD

**Issue by WillJW** [pozil/sfdc-ui-lookup-lwc#59]
In my use-case I need to access `_searchTerm` to get the original search term, rather than the clean version you get from `event.detail.searchTerm`.

The easiest way to do this would be to decorate `get getInputValue()` with `@api`, but you could also choose to convert `_searchTerm` to a public property: `@api searchTerm`.

If you agree this is a good idea, I can fork it using whichever option you prefer.

**Comment by pozil** [comment]
Hi @WillJW, can you tell me a bit more about your use case and why you need the raw search input?

**Comment by WillJW** [comment]
@pozil If no lookup item is found, I want to use the user input to populate a new form element, and allow the user to add a new item from there. At the moment, if a user searches for "My item", it gets populated in the new input as "my item" (lowercase).

**Comment by pozil** [comment]
Ok, I get it, that's a good use case.
Would exposing the raw search term as an attribute of the `searchchange` event work for you?

**Comment by WillJW** [comment]
@pozil Yeah, I think that would do it. Thanks.

**Comment by pozil** [comment]
Ok, I'll do that then. I want to keep the component's public signature as simple as possible.

**Comment by pozil** [comment]
@WillJW try this branch and let me know if it works for you:
https://github.com/pozil/sfdc-ui-lookup-lwc/tree/pozil/raw-search-term

If yes, I'll PR and merge it.

**Comment by WillJW** [comment]
@pozil That's perfect, thank you 👍

**Comment by pozil** [comment]
Cool. Feel free to use the new 2.3.0 version then.
