### ISSUE TITLE
Search Icon Position Consistency 

### ISSUE THREAD

**Issue by WaseemAliSabeel** [pozil/sfdc-ui-lookup-lwc#74]
Hi, firstly a big Thanks for the continuous updates to make this LWC better and reusable!
However, there is one UX discrepancy when you look at the position of the Search (magnifying glass) Icon which is placed on the RIGHT of the input field.
As one would observe in Global Search and in List View filter search, the  `utility:search` icon is positioned on the left.

I tried with changing the CSS of Line 370 in the JS  of getter method  `getSearchIconClass()` to 
        let css = 'slds-input__icon slds-input__icon_**left**' , but this doesnt seem to change the position of the icon.

Any suggestions/solutions to make this UI change ?
Thanks!

**Comment by pozil** [comment]
HI @WaseemAliSabeel and thanks for the feedback. The lookup component is based on the [SLDS lookup template](https://lightningdesignsystem.com/components/lookups/#site-main-content) which has the search icon on the right so I'm going to stick to that.

The global search and list view filters are not exactly base components so they have their own design. Perhaps this is an issue that you could take to the SLDS team?
