### ISSUE TITLE
Polymorphic "Related To" style lookup?

### ISSUE THREAD

**Issue by skycafemix** [pozil/sfdc-ui-lookup-lwc#75]
Thank you so much for your great work. I wonder if anyone has tried to create a polymorphic single selection lookup like the Related To field on activities? I received a request that might require it, and was wondering if it is something you have looked at before. 

I don't see it in SLDS, although in the SLDS release notes for June 6, 2016 it says "Lookups spec updated - Single and Polymorphic" so maybe they did once and took it out.. or maybe they mean multiple selection combo box by that entry. Haven't looked deeply but it seems a couple of people have tried it in Aura..

https://opfocus.com/salesforce-lightning-customizable-polymorphic-lookup-component/
https://github.com/veenasundara/Lightning-Polymorphic-Lookup

**Comment by pozil** [comment]
Good point, there's no such lookup blueprint on the SLDS website but the closest thing to this is the [global search template](https://lightningdesignsystem.com/guidelines/search/global/#site-main-content).

This project is based on the [SLDS lookup blueprint](https://lightningdesignsystem.com/components/lookups/#site-main-content) and I'd like to keep it that way to simplify maintenance and keep it future proof.

That being said, the project does support search on multiple object types (see example) but it doesn't have the dropdown to filter results per object type. You could implement this kind of functionality with a dropdown component next to it and the public properties/functions that this lookup exposes.

**Comment by skycafemix** [comment]
Understood, thank you for your reply. I see the Lookup blueprint does have something like that in the [Multi Entity version](https://lightningdesignsystem.com/components/lookups/#Multi-Entity) so something like that would work, else I'll roll my own if necessary. Best regards!
