### ISSUE TITLE
JS is case sensitive.

### ISSUE THREAD

**Issue by AliSiddiqui-CJ** [pozil/sfdc-ui-lookup-lwc#81]
In setSearchResults you are using result.id it should be result.Id ( 'I' should be capital) similarly you should change sel.id to sel.Id.

**Comment by pozil** [comment]
No need for that because objects passed to `setSearchResults` are not records but instances of `LookupSearchResult`. This class has a lowercase `id` attribute:
https://github.com/pozil/sfdc-ui-lookup-lwc/blob/master/src/main/default/classes/LookupSearchResult.cls#L6

**Comment by AliSiddiqui-CJ** [comment]
Yes that might be it! I couldn't find the LookupSearchResult class so I wrote my own and I used uppercase Id so it wasn't working for me. 
Thank you so much for this!
