### ISSUE TITLE
Extra Border class in LightningOut app

### ISSUE THREAD

**Issue by CiaranShocks** [pozil/sfdc-ui-lookup-lwc#82]
Pretty sure that the extra border should not appear but maybe theres a reason for this? It does disappear on focus.

Implementing as follows: `<c-lookup data-id="opportunity" placeholder="Search Salesforce" label="Opportunity" required="true" is-multi-entry={isMultiEntry} onsearch={opportunitySearch} onselectionchange={handleOpportunityChange}></c-lookup>`

![image](https://user-images.githubusercontent.com/6770541/120389812-d386d500-c324-11eb-93e8-3369673f825c.png)

**Comment by pozil** [comment]
Hi @CiaranShocks, I agree that the double border should not show up on empty selections.
The only case where it should be displayed is on single entry lookups when there's a value selected.

Unfortunately, I can't reproduce the issue that you described with the sample lookup app from this project. It renders without that double border for both single and multi-entry lookups. Can you give me some additional info to help me reproduce?

**Comment by CiaranShocks** [comment]
Sorry @pozil, I should have mentioned that I'm using the component within an app in LightningOut and just ran a quick test to confirm that the extra border only appears under those circumstances. Any idea on what could be up? There must be an extra class getting in somewhere. Thanks

**Comment by pozil** [comment]
Ah ok, that changes everything. Some CSS must be leaking in the lookup component. Could it be that you have a different version of SLDS vs what's provided in Lightning Experience?

**Comment by CiaranShocks** [comment]
I'm using the `<apex:includeLightning />` tag in VF for that so you would hope that it's the most recent version, let me check if I can add it manually
