### ISSUE TITLE
Enhancement: additional property searchObjects

### ISSUE THREAD

**Issue by rutgergernandt** [pozil/sfdc-ui-lookup-lwc#83]
First of all thanks for this great component! It is really thoroughly developed and a pleasure to read and work with. After playing around with it I have adjusted the component a little bit by adding an optional public property called searchObjects. Thereby it is possible to have the objectname bubble up with the search event (and create a more universal method and apex controller). Moreover, it is hereby possible to pass the onfocus of the input field up to the parent with this same object context, as a way to use the recentlyViewedMethod in this context. 

I thought this is the cleanest way of doing it, but perhaps there is a better way to implement this? Sharing it here because I preferably would not alter the component, to prevent getting out of sync for future updates. I think it would be a good addition to the help docs anyway if this use case is addressed, but I think it is quite common.

**Comment by pozil** [comment]
Hi @rutgergernandt thanks for the feedback.

I would rather not add an extra public property on the lookup to reduce the complexity and to maintain a separation of concern (only Apex needs to know about the SObjects).

However, you can easily add this information without modifying the Lookup core component. Here's how you can do this (example based from the sample code of this repo):

1. In the parent component that uses the lookup, add a dataset attribute that tracks the object name:
    ```xml
    <c-lookup
                    selection={initialSelection}
                    errors={errors}
                    onsearch={handleLookupSearch}
                    onselectionchange={handleLookupSelectionChange}
                    label="Search"
                    placeholder="Search Salesforce"
                    is-multi-entry={isMultiEntry}
                    new-record-options={newRecordOptions}
                    required
                    data-object-types="Account"
    >
    ```

1. in the parent JS, use the dataset attribute that you just added:

    ```js
    handleLookupSearch(event) {
            const lookupElement = event.target;
    
            alert(lookupElement.dataset.objectTypes);
    
           // Actual search code
    }
    ```

**Comment by rutgergernandt** [comment]
@pozil thanks for your answer, that indeed makes more sense! I still need to get used to this possibility and not a prof coder. Perhaps an idea to add it to the docs?

**Comment by pozil** [comment]
Good suggestion @rutgergernandt, I've added this to docs.
