### ISSUE TITLE
(Multiple) dependent lookups and recently viewed items 

### ISSUE THREAD

**Issue by rutgergernandt** [pozil/sfdc-ui-lookup-lwc#84]
This problem has two steps, possibly there is a better solution for step 1, which would possibly render step 2 unnecessary: 

**Step 1:** 
- The sample component sets the recently viewed items when the component is rendered, however, if the recent items are dependent they need to be fetched the moment the lookup becomes focussed. 
- The only way I could come up with to handle this, is to add an additional focus event to the lookup like this: 
```js
    handleFocus() {
        // Prevent action if selection is not allowed
        if (!this.isSelectionAllowed()) {
            return;
        }
        this._hasFocus = true;
        this._focusedResultIndex = null;
        this.dispatchEvent(new CustomEvent('focus')); //CUSTOM FOCUS EVENT
    }
```
- This works well, but the component itself needs to be altered... Would be great if this can be done differently of course. 

**Step 2:** 
- In a setup with a dependent lookup the search and recently viewed methods should use the new id after the selection change event. 
- E.g. something like this: 
```js
    selectedId; 
    handleSelectionChange(event){
        const selectedIds = event.detail;
        this.selectedId = selectedIds[0]; //This only works if you are not doing multiple select of course
    }

```
and 

```js
 handleRecentlyViewed(event) {
        let searchValues;
        let objectType = event.target.dataset.objectType;
        let objectTypeObject = {objectType: objectType};
        if (objectType === 'Object that is depending on some other object for selection') {
            let dependentRecordId = this.selectedId == undefined ? getFieldValue(this.someProperty.data, FIELD) : this.selectedId;
            let dependentRecordIdObject = {dependentRecordId: dependentRecordId};  
            searchValues = {...objectTypeObject, ...dependentRecordIdObject};
        } else { 
            searchValues = objectTypeObject;
        }
        getRecentlyViewed(searchValues)
            .then(results => {
                let lookup = this.template.querySelector(`c-lookup[data-object-type='${objectType}']`)
                if (lookup && results) {
                    lookup.setDefaultResults(results);
                }
            })
            .catch(error => {
                console.error('Lookup error', JSON.stringify(error));
                this.errors = [error];
            });
    }
```

- However, if the dependent field has already been selected and the field it is dependent on has changed, the setDefaultResults method will not update the _searchResults because it has a length > 0. 
- If the IF clause is removed, the focus prevents the selection of a record in the last (it seems only the last?) lookup in the component, because it gets focus again (not entirely sure why) 
- A dirty quick fix that seems to work is: 
```js
    @api
    setDefaultResults(results) {
        if (JSON.stringify(this._defaultSearchResults) !== JSON.stringify(results)) {
            this._defaultSearchResults = [...results];
        //if (this._searchResults.length === 0) { //REMOVED
            this.setSearchResults(this._defaultSearchResults);
        }
    }
```
- But it is, well, a dirty fix... 

Question: 
- is there any other way of doing this with the current component? (I guess it would be better to have separate methods for both functions in the end, which would make it possible to more closely resemble the 'normal' lookup too?) 

(And @pozil sorry to bother you again on such short notice, but as you see I am trying to squeeze the most out of the component!)

**Comment by pozil** [comment]
Hi @rutgergernandt. I'm not sure that you need anything new in the component to achieve a dependent lookup scenario but I'm open to discussing this.

My first take on this is that the `focus` event should be internal to the lookup since we only use it for rendering. What is exposed to a parent component is the `selectionchange` event.

Here's how I would implement the scenario that you described (disclaimer: I haven't tested the code so some minor adjustments may be needed):

```html
<c-lookup label="Lookup 1" class="lookup1" onselectionchange={handleLookup1Change}>
<c-lookup label="Lookup 2" class="lookup2">
```


```js
connectedCallback() {
  // Init lookup 1 initial selection and default results
  const lookup1 = document.querySelector('.lookup1');
  const lookup1Selection = []'; // Or any other value
  lookup1.selection = lookup1Selection; 
  lookup1.setDefaultResults([]); // Or any other value

  // Init lookup 2 default results
  resetLookup2DefaultResults(lookup1Selection); // Reusable method, see below
}

handleLookup1Change(event) {
  // Get lookup 1 selection
  const lookup1Selection = event.target.getSelection();
  
  // Get lookup 2 selection
  const lookup2 = document.querySelector('.lookup2');
  const lookup2Selection = lookup2.getSelection();

  // Clear lookup 2 if lookup 1 selection is not compatible with current value
  if (!isCompatible(lookup1SelectedIds, lookup2Selection)) {
     lookup2.selection = [];
  }

  // Calculate new default values for lookup 2
  resetLookup2DefaultResults(lookup1Selection);
}

handleLookup2Search(event) {
  // Get lookup 1 selection
  const lookup1 = document.querySelector('.lookup1');
  const lookup1Selection = lookup1.getSelection();

  // Get lookup 2 search info
  const lookup2Search = event.detail;

  // Run search in Apex with lookup 1 selection and search info from lookup 2
  apexSearch(lookup1Selection, lookup2Search)
        .then(results => {
            lookupElement.setSearchResults(results);
        })
        .catch(error => {
            // TODO: handle error
        });
}

resetLookup2DefaultResults(lookup1Selection) {
  // TODO: calculate default values based on lookup1Selection and save them in lookup2DefaultValues

  const lookup2 = document.querySelector('.lookup2');
  lookup2.setDefaultResults(lookup2DefaultValues)
}

```

**Comment by rutgergernandt** [comment]
@pozil thanks for your quick and elaborate answer! This makes a lot of sense, and indeed is a good solution that requires no further customization and is more scalable too with multiple lookup dependencies too. 

It is interesting to see your solution starts from untangling and then managing the possible different states of the component. This compared to a ('folk'? 'citizen'? or maybe just my personal 'intuitive') perspective that starts from at event 'x' we need variable 'y', how do we get it there at that very moment. Thanks for that lesson! I wouldn't have ended up there if the lookup component in the record edit view would have supported lookup dependencies and new records, but that was useful after all. 

I will try out to get it to work later this week (incl. the isCompatible function).

**Comment by pozil** [comment]
Sure, happy to help. This kind of perspective isn't natural but it will come with practice with LWC or other JS frameworks.
I'll close the issue for now.

**Comment by rutgergernandt** [comment]
I know the issue is closed, but for future reference: I think connectedCallback cannot be used here since the child components do not exist yet and therefore cannot be queried yet? In addition, it would not be possible to use the wire service in the connectedCallback to fetch data because it runs after the dom insertion. Therefore a getter seems more logical for the default value? But this leaves me guessing where to call the recent records method, because is suffers from the same problem of being to early in the component cycle? It is a pity I guess because this pattern would be very clear and readable.

**Comment by pozil** [comment]
Hi @rutgergernandt. Yes, you're right: you should use use `renderedCallback` instead of `connectedCallback` as this lifecycle hooks is triggered later in the [rendering flow](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.create_lifecycle_hooks).

**Comment by rutgergernandt** [comment]
I have opted for using a getter and smuggling in an extra helper function. The renderedCallback has the drawback of firing multiple times (and the docs state that it should not be used to set properties if I recall correctly). For completeness the solution I ended up with: 
   
```
<c-lookup selection={initialLookup1} onselectionchange={handleSelectionChange} ​onsearch={handleSearch} data-object-type="SomeObject1__c"> ​</c-lookup>
<c-lookup selection={initialLookup2} onsearch={handleSearch}​ data-object-type="SomeObject2__c" ​data-dependent-lookup="SomeObject1__c">​</c-lookup>
```

```
//Get initial selections & set default lookup values
get initialLookup1() {
        const id = getFieldValue(this.activiteit.data, SOME_FIELD1_ID);
        const object = 'SomeObject1__c';
        const icon = SOME_ICON1; //
        const title = getFieldValue(this.activiteit.data, SOME_FIELD1);
        this.setRecentlyViewed(object);
        return this.getSelection(id, object, icon, title);
    }
 get initialLookup2() {
        const id = getFieldValue(this.activiteit.data, SOME_FIELD2_ID);
        const object = 'SomeObject2__c';
        const icon = SOME_ICON2;
        const title = getFieldValue(this.activiteit.data, SOME_FIELD2);
        const dependentLookupId = getFieldValue(this.activiteit.data, SOME_FIELD1_ID);
        this.setRecentlyViewed(object, dependentLookupId);
        return this.getSelection(id, object, icon, title);
    }

    //Handle reset of dependent field
    handleSelectionChange(event) {
        const lookupObject = event.target.dataset.objectType;
        const dependentLookup = this.template.querySelector(`c-lookup[data-dependent-lookup='${lookupObject}']`); //Only works with a single dependent field 
        dependentLookup.selection = []; //clear selection 
        dependentLookup.setSearchResults([]); //clear current search results
        dependentLookup.setDefaultResults([]); //clear default results 
        const lookupId = event.detail;
        if (lookupId.length > 0) {
            const dependentLookupObject = dependentLookup.getAttribute("data-object-type")
            this.setRecentlyViewed(dependentLookupObject, lookupId[0]); //Only works with a single selection lookup
        } 
    }

  //Create a selection for the lookup record
    getSelection(id, sObject, icon, title) {
        let selection = [];
        if (id && sObject) {
            selection = [{
                id: id,
                sObjectType: sObject,
                icon: icon,
                title: title,
                subtitle: 'Not relevant in a selection'
            }];
        }
        return selection;
    };

    //Set the recently viewed records for this object
    setRecentlyViewed(objectType, dependentLookupId) {
        let searchValues = { objectType: objectType };
        if(dependentLookupId){searchValues.dependentLookupId = dependentLookupId};
        lookupRecentlyViewed(searchValues)
            .then(results => {
                let lookup = this.template.querySelector(`c-lookup[data-object-type='${objectType}']`)
                if (lookup) {
                    lookup.setDefaultResults(results);
                }
            })
            .catch(error => {
                console.error('Lookup error', JSON.stringify(error));
                this.errors = [error];
            });
    }
```
