### ISSUE TITLE
Making it required

### ISSUE THREAD

**Issue by UltimateRime** [pozil/sfdc-ui-lookup-lwc#9]
I've got this component as part of a form and was wondering if there is a way to make the field required in a similar way to lightning-input fields.

**Comment by pozil** [comment]
Hi @UltimateRime, I haven't incorporated validation logic in the lookup.
However, you can achieve that by expanding the selection event handling example I gave in the readme to show an error when the selection is empty.

You can implement something like that in the parent container (disclaimer: I haven't tested this code):

```js
handleSelectionChange(event) {
    const lookupElement = event.target;
    const selection = lookupElement.getSelection();
    if (selection.length === 0) {
        lookupElement.errors = [ 'This field is required' ];
        // TODO: add logic to mark form as invalid
    }
}
```

**Comment by ghiscoding** [comment]
in case someone else stumbles on the same issue

The following did **not** work and is sadly what was written in the sample code
```js
this.errors.push({ message: 'Complete this field.' }); // doesn't work
// or
this.errors.push('Complete this field.'); // doesn't work
```

But the following does work, so it's similar to the suggested (non-tested) code with a slight change and finally it works :)
```js
lookupElement.errors = [{ message: 'Complete this field.' }];
```
