### ISSUE TITLE
Handling Initial Selection Scenarios

### ISSUE THREAD

**Issue by Bobbygllh** [pozil/sfdc-ui-lookup-lwc#95]
Hi,
First off, component is awesome, extremely powerful. My issue is more of a question, I am wondering how to most optimally handle scenarios where we sometimes have an initial selection and then sometimes do not. Currently I have two c-lookup components and am rendering the correct one based upon if the record has a record in that lookup and then the other one when the record does not
<img width="567" alt="Screen Shot 2022-01-20 at 7 29 19 AM" src="https://user-images.githubusercontent.com/30133002/150339163-0f698a55-405b-4258-9a77-b28f5ee19587.png">

id prefer to just use one instance of the c-lookup component and have it just be a standard lookup if the selection object is null/undefined. Is there a trick to doing this?

**Comment by pozil** [comment]
Hi @Bobbygllh thanks for the kind feedback.

All you need is a getter in your component with code like this:

```js
get initialLookupSelection() {
  // Return an empty array if there's no inital selection
  return this.dataItem.additions.initialselection ? this.dataItem.additions.initialselection : [];
}
```

```html
<c-lookup selection={initialLookupSelection} ...
```

**Comment by Bobbygllh** [comment]
@pozil Awesome, thank you!
